'use client';

/**
 * SpecForge — Landing Page
 * src/app/page.tsx
 * TASK-009/010 | Owner: architect
 */

import { IdeaInput } from '@/components/IdeaInput';

const AGENTS = [
  { name: 'Strategist', color: 'from-yellow-500 to-orange-500', desc: 'PRD · Personas · Stories' },
  { name: 'Architect', color: 'from-purple-500 to-violet-500', desc: 'ADRs · Design Spec' },
  { name: 'Engineer', color: 'from-green-500 to-emerald-500', desc: 'Tasks · Scaffolding' },
  { name: 'Copywriter', color: 'from-pink-500 to-rose-500', desc: 'GTM · Pitch Deck' },
  { name: 'QA Sentinel', color: 'from-red-500 to-orange-500', desc: 'Tests · Risk Register' },
  { name: 'Orchestrator', color: 'from-blue-500 to-cyan-500', desc: 'DAG · Self-Assembly' },
];

export default function Home() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-950 to-slate-900">
      <div className="container mx-auto px-4 py-24 flex flex-col items-center gap-16">
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-purple-500/20 border border-purple-500/30 text-purple-300 text-sm font-medium">
          <span className="w-2 h-2 rounded-full bg-purple-400 animate-pulse" />
          Self-Assembling Product Engine · Powered by Complete.dev
        </div>
        <div className="text-center space-y-6 max-w-4xl">
          <h1 className="text-6xl md:text-8xl font-bold text-white tracking-tight leading-none">
            Idea to Product Package
            <span className="block text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-400">in Minutes.</span>
          </h1>
          <p className="text-xl text-slate-400 max-w-2xl mx-auto leading-relaxed">
            SpecForge deploys 6 AI agents in parallel to transform your raw idea into a complete product package.
          </p>
        </div>
        <IdeaInput />
        <div className="w-full max-w-4xl">
          <p className="text-center text-xs text-slate-500 uppercase tracking-widest mb-6">Your agent team assembles automatically</p>
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">
            {AGENTS.map((agent) => (
              <div key={agent.name} className="flex flex-col items-center gap-3 p-4 rounded-2xl bg-white/5 border border-white/10 hover:bg-white/10 transition-all">
                <div className={`w-10 h-10 rounded-full bg-gradient-to-br ${agent.color} flex items-center justify-center text-white font-bold text-sm shadow-lg`}>{agent.name[0]}</div>
                <div className="text-center">
                  <p className="text-white text-xs font-semibold">{agent.name}</p>
                  <p className="text-slate-500 text-xs mt-1">{agent.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
        <div className="w-full max-w-3xl p-6 rounded-2xl bg-gradient-to-r from-purple-900/50 to-pink-900/50 border border-purple-500/30">
          <p className="text-center text-slate-300 text-sm">
            <span className="text-purple-400 font-semibold">Meta proof:</span>{' '}
            Every artifact in this submission was generated by SpecForge itself, running inside Complete.dev.
          </p>
        </div>
      </div>
    </main>
  );
}
